
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
/*
 * @author Khattak01
 */
public class ClientMain extends javax.swing.JFrame {

    /**
     * Creates new form ClientMain
     */
    static InputStreamReader myclient_isr;
    static BufferedInputStream myclient_bis;
    static BufferedReader  myclient_br;
    static String Filename;
    static Socket myclient_socket;
    static InputStream myclient_is;
    static String server_IpAddress;
    static PrintWriter myclient_pw;
    static BufferedOutputStream myclient_bos;
    static FileOutputStream myclient_fos;
    static byte myclientBytes[];
    static int bytesRead;
    public ClientMain() throws IOException 
    {
        displayLogin();
        JOptionPane.showMessageDialog(null,"You can download a file only if have an account and logged", "InfoBox: " , JOptionPane.INFORMATION_MESSAGE);
        server_IpAddress = "127.0.0.1";
        myclient_socket= new Socket(server_IpAddress, 8888);
        myclient_isr= new InputStreamReader(System.in);
        myclient_br = new BufferedReader(myclient_isr);
        myclient_pw=new PrintWriter(myclient_socket.getOutputStream(), true);
        Scanner var= new Scanner(System.in);
        DataInputStream input = new DataInputStream(myclient_socket.getInputStream());
        DataOutputStream output = new DataOutputStream(myclient_socket.getOutputStream());
        /*System.out.println("\nEnter your username and password to login to your account."); 
        System.out.println("Enter USERNAME : ");
        /*String user = var.nextLine();
        output.writeUTF(user);
        System.out.println(input.readUTF());*/
        //BufferedOutputStream myserver_bos= new BufferedOutputStream(myclient_socket.getOutputStream());
        System.out.println("Welcome to your Social network site!");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        v_mem = new javax.swing.JButton();
        c_acc = new javax.swing.JButton();
        t_con = new javax.swing.JButton();
        about = new javax.swing.JButton();
        ext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        savingPath = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        file_name = new java.awt.TextField();
        ext1 = new javax.swing.JButton();
        c_acc1 = new javax.swing.JButton();
        c_acc2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Client");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 235, 67));

        v_mem.setBackground(new java.awt.Color(255, 255, 255));
        v_mem.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        v_mem.setText("Login");
        v_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_memActionPerformed(evt);
            }
        });
        getContentPane().add(v_mem, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 100, 235, 63));

        c_acc.setBackground(new java.awt.Color(255, 255, 255));
        c_acc.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        c_acc.setText("LogOut");
        c_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_accActionPerformed(evt);
            }
        });
        getContentPane().add(c_acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 120, 30));

        t_con.setBackground(new java.awt.Color(255, 255, 255));
        t_con.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        t_con.setText("Term & Condition");
        getContentPane().add(t_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 235, 68));

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        getContentPane().add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 235, 66));

        ext.setBackground(new java.awt.Color(255, 255, 255));
        ext.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        ext.setForeground(new java.awt.Color(200, 22, 25));
        ext.setText("EXIT");
        ext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extMouseClicked(evt);
            }
        });
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        getContentPane().add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1057, 569, 66, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("File Transfer Application");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 235, 67));

        savingPath.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        savingPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingPathActionPerformed(evt);
            }
        });
        getContentPane().add(savingPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 280, 30));

        label1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        label1.setText("Path for saving FILES:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 190, 30));

        label2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        label2.setText("FILE name :");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 190, 30));

        file_name.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        file_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_nameActionPerformed(evt);
            }
        });
        getContentPane().add(file_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 280, 30));

        ext1.setBackground(new java.awt.Color(255, 255, 255));
        ext1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        ext1.setForeground(new java.awt.Color(200, 22, 25));
        ext1.setText("EXIT");
        ext1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ext1MouseClicked(evt);
            }
        });
        ext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ext1ActionPerformed(evt);
            }
        });
        getContentPane().add(ext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 70, 30));

        c_acc1.setBackground(new java.awt.Color(255, 255, 255));
        c_acc1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        c_acc1.setText("Register");
        c_acc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_acc1ActionPerformed(evt);
            }
        });
        getContentPane().add(c_acc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 235, 63));

        c_acc2.setBackground(new java.awt.Color(255, 255, 255));
        c_acc2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        c_acc2.setText("Done");
        c_acc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_acc2ActionPerformed(evt);
            }
        });
        getContentPane().add(c_acc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void c_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_accActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_accActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutActionPerformed

    private void extMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseClicked
        System.exit(0);
    }//GEN-LAST:event_extMouseClicked

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_extActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void v_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_memActionPerformed
        displayLogin();
    }//GEN-LAST:event_v_memActionPerformed

    private void savingPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingPathActionPerformed

    private void file_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file_nameActionPerformed

    private void ext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ext1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_ext1MouseClicked

    private void ext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ext1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ext1ActionPerformed

    private void c_acc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_acc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_acc1ActionPerformed

    private void c_acc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_acc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_acc2ActionPerformed
private static void displayLogin() {
        JTextField field1 = new JTextField("");
        JTextField field2 = new JTextField("");
        JButton btnRegister = new JButton("Register>>");
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(btnRegister);
        panel.add(new JLabel("Username:"));
        panel.add(field1);
        panel.add(new JLabel("Password:"));
        panel.add(field2);
        //panel.add(new JLabel(""));
        JButton btn = new JButton("Login");
        panel.add(btn);
        int result = JOptionPane.showConfirmDialog(null, panel, "Register",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println(field1.getText()
                + " " + field2.getText());
        } else {
            System.out.println("Cancelled");
        }
    }
private static void displayRegister() {
        JTextField field1 = new JTextField("");
        JTextField field2 = new JTextField("");
        JTextField field3 = new JTextField("");
        JPanel panel = new JPanel(new GridLayout(0, 1)); 
        panel.add(new JLabel("Username:"));
        panel.add(field1);
        panel.add(new JLabel("Password:"));
        panel.add(field2);
        panel.add(new JLabel("Reenter Password:"));
        panel.add(field3);
        int result = JOptionPane.showConfirmDialog(null, panel, "Register",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println(field1.getText()
                + " " + field2.getText());
        } else {
            System.out.println("Cancelled");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClientMain().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ClientMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton c_acc;
    private javax.swing.JButton c_acc1;
    private javax.swing.JButton c_acc2;
    private javax.swing.JButton ext;
    private javax.swing.JButton ext1;
    private java.awt.TextField file_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField savingPath;
    private javax.swing.JButton t_con;
    private javax.swing.JButton v_mem;
    // End of variables declaration//GEN-END:variables
}
